apiVersion: v1
kind: Service
metadata:
  name: routerless-lb
  labels:
    env: prod
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: traefik