apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: another-hello-world-server
  labels:
    product: another-hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: another-hello-world
    spec:
      containers:
      - name: hello-world
        image:  us.gcr.io/rookoutdev/traefik-hello-world:latest
        ports:
          - containerPort: 5000
        env:
          # Define the environment variable
          - name: BACKGROUND_COLOR
            value: "red"
          # Define the environment variable
          - name: TITLE
            value: "IM ANOTHER BACKEND SERVER"
